import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ReactNode } from 'react'
import FindMeHeader from '@/components/find-me/layouts/Header'
import FindMeFooter from '@/components/find-me/layouts/Footer'

import './globals.css'
import '../css/find-me/index.css'
import '../css/find-me/global.css'
import FindMeLayout from '@/components/find-me/layouts/layout'
import { fetchAssessmentUserCount } from '@/service/assessment'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Repo = {
  name: string
  stargazers_count: number
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <FindMeLayout>{children}</FindMeLayout>
      </body>
    </html>
  )
}
